### ISSUE TITLE
trVAE runs very slow for large datasets

### ISSUE THREAD

**Issue by chansigit** [theislab/scarches#101] opened 2022-03-25 12:57 UTC
I am training a trVAE model on a dataset containing 800k cells but it is extremely slow. Any tricks speeding up the training process?

**Comment by Koncopd** [comment] 2022-04-19 11:26
It should be resolved in 0.5.2, feel free to reopen if not.

**Closed by Koncopd** 2022-04-19 11:26 UTC

**Comment by dmalzl** [comment] 2022-08-30 17:24
I have a similar issue with version 0.5.4 and a dataset of 164k cells. `torch.cuda.is_available` returns True but a single iteration seems to take roughly an hour. I run it in the same configuration as described in [`trVAE_zenodo_pipeline.ipynb`](thttps://github.com/theislab/scarches/blob/master/notebooks/trVAE_zenodo_pipeline.ipynb) using 4000 HVGs. Do you have an idea why this is?

**Comment by dmalzl** [comment] 2022-08-30 17:28
comparing CPU vs GPU utilisation it seems like there is a problem in using the GPU since CPU is 100% while GPU is only around 17%. Could it be a problem related to the a problem with with pytorch such as erroneous GPU initialisation (i.e. maybe torch does not know that it should use the GPU)?

**Comment by Koncopd** [comment] 2022-08-30 18:07
Hi, @dmalzl . No, i don't think it is the case. I am sure the GPU is used. The utilization could reduce because of the heating and other things.

**Comment by dmalzl** [comment] 2022-08-30 18:12
Hmm, I don't think this is the case. The GPU is part of a compute cluster and runs as expected with scVI.

**Comment by Koncopd** [comment] 2022-08-30 18:35
Hm, strange, but i also observed utilization drop on different pytorch models not related to scArches. Does it happen immediately or after some time?

**Comment by dmalzl** [comment] 2022-08-30 18:41
This is right from the start. Pytorch version is 1.11.0+cu113. I haven't actually looked at the scVI GPU usage but the same data runs at around 10 seconds per iteration so I assume it is fully loaded.

**Comment by M0hammadL** [comment] 2022-08-30 18:45
@dmalzl  is Mmd= True if yes that is the bottleneck

**Comment by Koncopd** [comment] 2022-08-30 18:46
`use_mmd=True` by default.

**Comment by dmalzl** [comment] 2022-08-30 18:47
Yes. I will try without tomorrow. Out of curiosity, do you know why this is.

**Comment by Koncopd** [comment] 2022-08-30 18:47
It is very computationally expensive to calculate.

**Comment by M0hammadL** [comment] 2022-08-30 18:49
> It is just very computationally intensive.

Exactly @chansigit @Koncopd

**Comment by dmalzl** [comment] 2022-08-30 18:53
Does this profit from multiple CPUs? If so one should either document this or change the default to false to ease use.

**Comment by dmalzl** [comment] 2022-08-30 18:53
Anyway. Thanks for the help :) Will report if the issue is solved tomorrow

**Comment by Koncopd** [comment] 2022-08-30 18:54
I don"t think it uses multiple CPUs. Yes, we will change the defaults.

**Comment by dmalzl** [comment] 2022-08-31 07:37
setting `use_mmd = False` did the trick. Thanks

**Comment by johnmous** [comment] 2022-11-02 12:24
> 

Yes, much faster now. But what are the implications of this?
