### ISSUE TITLE
ImportError: cannot import name 'container_abcs' from 'torch._six'

### ISSUE THREAD

**Issue by cdedonno** [theislab/scarches#75] opened 2021-07-23 16:16 UTC
Hey guys,

I am encountering this error when importing scarches

```
>>> import scarches
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq_cuda/lib/python3.8/site-packages/scArches-0.3.5-py3.8.egg/scarches/__init__.py", line 1, in <module>
    from . import dataset, metrics, trainers, models, zenodo, plotting
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq_cuda/lib/python3.8/site-packages/scArches-0.3.5-py3.8.egg/scarches/trainers/__init__.py", line 1, in <module>
    from .trvae.unsupervised import trVAETrainer
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq_cuda/lib/python3.8/site-packages/scArches-0.3.5-py3.8.egg/scarches/trainers/trvae/unsupervised.py", line 1, in <module>
    from .trainer import Trainer
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq_cuda/lib/python3.8/site-packages/scArches-0.3.5-py3.8.egg/scarches/trainers/trvae/trainer.py", line 10, in <module>
    from ._utils import make_dataset, custom_collate, print_progress
  File "/home/icb/carlo.dedonno/anaconda3/envs/lataq_cuda/lib/python3.8/site-packages/scArches-0.3.5-py3.8.egg/scarches/trainers/trvae/_utils.py", line 5, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' (/home/icb/carlo.dedonno/anaconda3/envs/lataq_cuda/lib/python3.8/site-packages/torch/_six.py)
```

This is happening with any pytorch version newer than 1.8.0, I have currently installed version 1.9.0 in my environment. 

Could you take a look at this?

**Comment by Koncopd** [comment] 2021-07-23 19:04
Fixed on master.

**Comment by LisaSikkema** [comment] 2022-03-18 15:11
So what was the fix for this? I'm encountering the same problem actually with v0.3.6

**Comment by LisaSikkema** [comment] 2022-03-18 15:23
Okay yes that seems to fix it, maybe adapt your requirements file there? (As we're recommending HLCA users to install this scArches version, still helpful to update this "outdated" version :) )

**Comment by Koncopd** [comment] 2022-03-19 10:10
The latest version of scarches (0.5.1) doesn't have the bug. Why using v0.3.5 actually?

**Comment by LisaSikkema** [comment] 2022-03-21 09:43
This is the version we used for the Human Lung Cell Atlas (it was the newest version when we started our analysis), and for reproducibility purposes we stuck to that version, and we suggest people who want to map their data to the atlas to use the same version.

**Comment by LisaSikkema** [comment] 2022-03-21 09:51
But open for discussion there, if you would say absolutely nothing about the algorithm changed since then, we could consider moving to the latest version. Just noticed that arguments etc. are already different

**Comment by Koncopd** [comment] 2022-03-21 10:07
Ok, i see,  for 0.3.5 try to install pytorch==1.3 and scvi-tools==0.8.1 before installing scarches.

**Closed** 2022-05-10 13:52 UTC
